version: "3"
services:
  app:
    restart: always
    build: . # Current directory!
    command: "./wait-for-mysql.sh" # "python3 manage.py runserver 0.0.0.0:8000", "python3 manage.py makemigrations", "python3 manage.py migrate","python3 manage.py db_populate",
    volumes:
      - .:/code
    ports:
      - "3000:8000"
    depends_on:
      - db
  db:
    image: mysql:latest
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - "./mysql:/var/lib/mysql"
    expose: 
      - "3306"
    ports:
      - "3306:3306"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=secret123
      - MYSQL_DATABASE=django_app
      - MYSQL_USER=django_app
      - MYSQL_PASSWORD=django_app123